name: causal-inference-iot
channels:
  - conda-forge
dependencies:
  - jupyter 
  - lightgbm
  - matplotlib
  - mlxtend
  - networkx
  - openpyxl
  - pandas
  - pip >= 24.0
  - py-xgboost
  - pyarrow
  - python >= 3.11
  - scikit-learn
  - selenium
  - xgboost
  - pip:
      - igraph
      - lxml
      - plotly
      - seaborn